import { useI18n } from '../../../../lang/useI18n';

export enum BCP47 {
  AR_SA = 'ar-SA',
  CA_SZ = 'cs-CZ',
  DA_DK = 'da-DK',
  DE_DE = 'de-DE',
  EL_GR = 'el-GR',
  EN_AU = 'en-AU',
  EN_GB = 'en-GB',
  EN_IE = 'en-IE',
  EN_US = 'en-US',
  EN_ZA = 'en-ZA',
  ES_ES = 'es-ES',
  ES_MX = 'es-MX',
  FI_FI = 'fi-FI',
  FR_CA = 'fr-CA',
  FR_FR = 'fr-FR',
  HE_IL = 'he-IL',
  HI_IN = 'hi-IN',
  HU_HU = 'hu-HU',
  ID_ID = 'id-ID',
  IT_IT = 'it-IT',
  JA_JP = 'ja-JP',
  KO_KR = 'ko-KR',
  NL_BE = 'nl-BE',
  NL_NL = 'nl-NL',
  NO_NO = 'no-NO',
  PL_PL = 'pl-PL',
  PT_BR = 'pt-BR',
  PT_PT = 'pt-PT',
  RO_RO = 'ro-RO',
  RU_RU = 'ru-RU',
  SK_SK = 'sk-SK',
  SV_SE = 'sv-SE',
  TH_TH = 'th-TH',
  TR_TR = 'tr-TR',
  ZH_CN = 'zh-CN',
  ZH_HK = 'zh-HK',
  ZH_TW = 'zh-TW',
}

export const LangOptions = (t: ReturnType<typeof useI18n>['t']) =>
  Object.values(BCP47).map((value) => ({
    value,
    label: t(`pages.captions.langOptions.${value}`),
  }));
