name: Release
on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
        # TODO Fix later
        # platform: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install webkit2gtk (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y webkit2gtk-4.0 libaytana-appindicator3-dev

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node and Cache .pnpm-store
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Rust setup
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build 🔧
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY}}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD}}
        with:
          # the action automatically replaces __VERSION__ with the app version
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          releaseDraft: true
          releaseBody: "See the assets to download this version and install."
          prerelease: false
          includeDebug: true
          includeUpdaterJson: true
          tauriScript: 'pnpm'
